#!/bin/bash

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch =~ master|main|develop|development ]]; then
    message="Please don't commit directly to $current_branch."
    echo -e "\033[1;31mERROR: $message\033[0m";
    exit 1
fi
