export enum ActionTypes {
  R_UPDATE_PROCESSING_STATUS = 'app/R_UPDATE_PROCESSING_STATUS',
  R_UPDATE_BOOTING_STATUS = 'app/R_UPDATE_BOOTING_STATUS',
  R_UPDATE_SETUP_STATUS = 'app/R_UPDATE_SETUP_STATUS',
}
