export enum ActionTypes {
  R_CREATE_NEW_USER = 'user/R_CREATE_NEW_USER',
  R_UPDATE_USERNAME = 'user/R_UPDATE_USERNAME',
  R_UPDATE_USER = 'user/R_UPDATE_USER',
  R_CLEAR_USER = 'user/R_CLEAR_USER',
}
