export enum ActionTypes {
  R_CREATE_NEW_USER = 'user/R_CREATE_NEW_USER',
  R_UPDATE_USERNAME = 'user/R_UPDATE_USERNAME',
  R_UPDATE_USER = 'user/R_UPDATE_USER',
  R_CLEAR_USER = 'user/R_CLEAR_USER',
  R_UPDATE_PROGRAM_SCHEDULE = 'user/R_UPDATE_PROGRAM_SCHEDULE',
  R_ADD_NEW_RECORD_GROUP = 'user/R_ADD_NEW_RECORD_GROUP',
  R_UPDATE_PROGRAM_PROGRESS = 'user/R_UPDATE_PROGRAM_PROGRESS',
}
