# This is a basic workflow to help you get started with Actions

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint . --ext .ts,.tsx
